/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javabeans.seeallmenu;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * FormEdit.java
 * JFrame untuk mengedit data menu yang sudah ada.
 * Form ini memungkinkan pengguna untuk mengubah nama, kategori, harga,
 * serta mengganti gambar menu. Perubahan akan disimpan ke database MySQL.
 * Form ini juga mendukung validasi input dasar seperti pengecekan nama, harga,
 * dan pemilihan kategori yang sesuai.
 *
 * @author HAFIS HENDRIANSYAH
 */
public class FormEdit extends javax.swing.JFrame {
    private String selectedImagePath;
    private Runnable refreshCallback;
    
    // private int id_menu;

    /**
     * Konstruktor default, hanya digunakan untuk testing standalone.
     */
    public FormEdit() {
        initComponents();
    }
    
    /**
     * Konstruktor dengan callback penyegaran.
     * Digunakan agar saat data berhasil diubah, halaman sebelumnya bisa diperbarui otomatis.
     *
     * @param refreshCallback Runnable yang akan dijalankan setelah data berhasil disimpan
     */
    public FormEdit(Runnable refreshCallback) {
        initComponents();
        this.refreshCallback = refreshCallback;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNamaMenu = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        cmbKategori = new javax.swing.JComboBox<>();
        btnChooseImage = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblGambar = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Edit");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 243, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 52, 46));
        jLabel1.setText("Edit Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 34, -1, -1));
        jPanel1.add(txtNamaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 130, 240, 29));
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 226, 240, 29));

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Category", "Coffee", "Non-Coffee", "Snack", "Food" }));
        jPanel1.add(cmbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 178, 240, 29));

        btnChooseImage.setText("Choose Image");
        btnChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseImageActionPerformed(evt);
            }
        });
        jPanel1.add(btnChooseImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 274, 121, 29));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(78, 52, 46));
        jLabel2.setText("Name Menu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 129, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(78, 52, 46));
        jLabel3.setText("Category");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 177, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(78, 52, 46));
        jLabel4.setText("Price");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 225, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(78, 52, 46));
        jLabel5.setText("Choose Image");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 273, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 389, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 389, -1, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 389, -1, -1));
        jPanel1.add(lblGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 321, 183, 62));

        lblID.setText("jLabel6");
        jPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 105, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("ID Menu");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 98, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabeansmanagementsystem/images/gambar biji kopi.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, -50, 420, 360));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabeansmanagementsystem/images/gambar biji kopi.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 280, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Event handler untuk tombol "Save".
     * Melakukan validasi data, dan menyimpan perubahan data ke database.
     * Menampilkan pesan sukses atau error menggunakan JOptionPane.
     *
     * @param evt event klik tombol
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String id_menu = lblID.getText();
        String namaMenu = txtNamaMenu.getText().trim();
        String kategoriMenu = cmbKategori.getSelectedItem().toString().trim();
        String harga = txtHarga.getText().trim();
        
        if (namaMenu.isEmpty() || kategoriMenu.isEmpty() || harga.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data can not be empty!", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (namaMenu.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(this, "Menu name must not contain numbers", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(cmbKategori.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Please select a category", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!harga.matches("\\d+(\\.\\d+)?")){
             JOptionPane.showMessageDialog(this, "Price must contain only numbers", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javabeans", "root", "");
            String sql = "UPDATE javabeans_menu SET category_menu = ?, nama_menu = ?, harga_menu = ?, gambar_menu = ? WHERE id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, kategoriMenu);
            pst.setString(2, namaMenu);
            pst.setString(3, harga);
            pst.setInt(5, Integer.parseInt(id_menu));
            
        
            if (selectedImagePath != null){
                FileInputStream fis = new FileInputStream(new File(selectedImagePath));
                pst.setBinaryStream(4, fis, (int) new File(selectedImagePath).length());
            } else {
                pst.setNull(4, java.sql.Types.BLOB);
            }

            
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Success! Your data has been updated");
            refreshCallback.run();
            
            txtNamaMenu.setText("");
            txtHarga.setText("");
            cmbKategori.setSelectedIndex(0);
            lblGambar.setIcon(null);
            selectedImagePath = null;
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    
    /**
     * Event handler untuk tombol "Choose Image".
     * Membuka file chooser dan menampilkan gambar yang dipilih ke dalam JLabel.
     * Menyimpan path gambar terpilih ke variabel untuk disimpan ke database.
     *
     * @param evt event klik tombol
     */
    private void btnChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseImageActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih Gambar");
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Gambar (JPG, PNG, JPEG)", "jpg", "png", "jpeg");
        fileChooser.setFileFilter(filter);
        
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();

        // Tampilkan gambar ke JLabel (misalnya lblGambar adalah JLabel kamu)
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));
            lblGambar.setIcon(imageIcon);

        // (Opsional) Simpan path ke variabel untuk disimpan ke database nanti
            selectedImagePath = selectedFile.getAbsolutePath();
            System.out.println("Path gambar: " + selectedImagePath);
        }
    }//GEN-LAST:event_btnChooseImageActionPerformed
    
    /**
     * Event handler untuk tombol "Clear".
     * Mengosongkan semua input, reset dropdown dan menghapus gambar dari tampilan.
     *
     * @param evt event klik tombol
     */
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    // TODO add your handling code here:
        txtNamaMenu.setText("");
        txtHarga.setText("");
        cmbKategori.setSelectedIndex(0);
        lblGambar.setIcon(null);
        selectedImagePath = null;
    }//GEN-LAST:event_btnClearActionPerformed
    
    /**
     * Event handler untuk tombol "Cancel".
     * Menutup form saat ini.
     *
     * @param evt event klik tombol
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    
    /**
     * Mengisi data menu ke dalam form berdasarkan data dari database.
     *
     * @param id ID menu
     * @param kategori kategori menu
     * @param nama nama menu
     * @param harga harga menu
     * @param gambarPath path gambar menu
     */
    public void setData(int id, String kategori, String nama, int harga, String gambarPath){
        lblID.setText(String.valueOf(id));
        txtNamaMenu.setText(nama);
        txtHarga.setText(String.valueOf((int)harga));
        cmbKategori.setSelectedItem(kategori);
        selectedImagePath = gambarPath;
        lblGambar.setIcon(new ImageIcon(gambarPath));
    }
    
    /**     
     * Fungsi main untuk menampilkan FormEdit secara mandiri.
     * Biasanya hanya digunakan untuk keperluan pengujian.
     *
     * @param args argumen baris perintah
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChooseImage;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNamaMenu;
    // End of variables declaration//GEN-END:variables
}