/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javabeans.login;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javabeans.model.Koneksi;
import java.sql.*;
import javabeans.signup.FormSignUp;
import javabeans.homepage.HomePageFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author HAFIS HENDRIANSYAH
 * 
 * Kelas ini merupakan tampilan antarmuka (form) login grafis menggunakan Java Swing.
 * Pengguna diminta memasukkan username dan password, kemudian diverifikasi menggunakan
 * objek dari kelas Login.
 * 
 * Jika berhasil, akan ditampilkan pesan login berhasil. Jika gagal, akan muncul pesan kesalahan.
 * 
 * Form ini terdiri dari: 
 * - Label Username & Password
 * - Text field dan password field
 * - Tombol Login
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     * Konstruktor FormLogin
     * Menginisialisasi komponen GUI dan menempatkan form di tengah layar.
     */
    public FormLogin() {
        initComponents(); // Inisialisasi komponen UI bawaan NetBeans
        setLocationRelativeTo(null); // Menempatkan form di tengah layar
        setResizable(false); // Mencegah form diubah ukurannya
    
    // Atur fokus awal ke panel utama
    this.addWindowFocusListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowGainedFocus(java.awt.event.WindowEvent e) {
            jPanel1.requestFocusInWindow(); // Panel atau komponen lain sebagai fokus awal
        }
    });
    
    // Awalnya password tidak ditampilkan sebagai ●
    txtPasswordLog.setEchoChar((char) 0); // Biar tulisan Password terlihat

    // Placeholder behavior untuk jTextField1 (Username)
    txtUsernameLog.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtUsernameLog.getText().equals("Username")) {
                txtUsernameLog.setText("");
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtUsernameLog.getText().isEmpty()) {
                txtUsernameLog.setText("Username");
            }
        }
    });

    // Placeholder behavior untuk jPasswordField1 (Password)
    txtPasswordLog.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            String pass = new String(txtPasswordLog.getPassword());
            if (pass.equals("Password")) {
        txtPasswordLog.setText("");
            if (cbxShowPassword.isSelected()) {
            txtPasswordLog.setEchoChar((char) 0);
        } else {
            txtPasswordLog.setEchoChar('●');
            }
        }
    }
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            String pass = new String(txtPasswordLog.getPassword());
            if (pass.isEmpty()) {
                txtPasswordLog.setText("Password");
                txtPasswordLog.setEchoChar((char) 0); // Tampilkan teks biasa lagi
            }
        }
    });
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtUsernameLog = new javax.swing.JTextField();
        txtPasswordLog = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        cbxShowPassword = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(78, 52, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hello,");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 103, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 153, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("to JavaBeans Management System.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 203, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 243, 224));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsernameLog.setBackground(new java.awt.Color(255, 243, 224));
        txtUsernameLog.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUsernameLog.setForeground(new java.awt.Color(78, 52, 41));
        txtUsernameLog.setText("Username");
        txtUsernameLog.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 52, 46), 3, true));
        txtUsernameLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameLogActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsernameLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 200, 30));

        txtPasswordLog.setBackground(new java.awt.Color(255, 243, 224));
        txtPasswordLog.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPasswordLog.setForeground(new java.awt.Color(78, 52, 41));
        txtPasswordLog.setText("Password");
        txtPasswordLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(78, 52, 46), 3));
        txtPasswordLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordLogActionPerformed(evt);
            }
        });
        jPanel2.add(txtPasswordLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 200, 30));

        btnLogin.setBackground(new java.awt.Color(100, 73, 38));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, 30));

        btnSignUp.setBackground(new java.awt.Color(249, 242, 213));
        btnSignUp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(78, 52, 46));
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 90, 30));

        cbxShowPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxShowPassword.setText("Show Password");
        cbxShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxShowPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(cbxShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabeansmanagementsystem/images/gambar biji kopi.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 270, 360));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 19, 420, 360));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabeansmanagementsystem/images/logo-java-beans.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 19, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameLogActionPerformed

    private void txtPasswordLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordLogActionPerformed
    
    /**
     * Event handler untuk tombol Login.
     * Mengambil input username dan password dari field,
     * lalu membuat objek Login dan memanggil cekLogin().
     * 
     * @param evt Event dari tombol login ditekan.
     */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsernameLog.getText();
        String password = new String(txtPasswordLog.getPassword());
        String passwordHash = passwordHash(password); // Hash password untuk dicocokkan dengan database
        
        // Validasi kosong
        if (username.equals("Username") || password.equals("Password") || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username and password can not be empty", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Validasi panjang password
        if(password.length() < 8){
            JOptionPane.showMessageDialog(this, "Password atleast 8 characters", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Login login = new Login(username, passwordHash);
        
        try {
           // Koneksi ke database
           Connection conn = Koneksi.getConnection();
           String query = "SELECT * FROM javabeans_akun WHERE username=? AND password_user=?";
           PreparedStatement preparedStat = conn.prepareStatement(query);
           preparedStat.setString(1, login.username);
           preparedStat.setString(2, login.password);
           ResultSet resultSet = preparedStat.executeQuery();   
           
        if (resultSet.next()) {
            // Login berhasil, ambil ID dan buka HomePage
            int idUser = resultSet.getInt("id_user");
            JOptionPane.showMessageDialog(this, "Hello, " + login.username, "Message", JOptionPane.INFORMATION_MESSAGE);
            HomePageFrame home = new HomePageFrame(idUser);
            home.setVisible(true);
            this.dispose();
        } else {
            // Gagal login
            JOptionPane.showMessageDialog(this, "Username or Password wrong", "Warning", JOptionPane.ERROR_MESSAGE);
        }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    
    /**
     * Melakukan hash pada password menggunakan algoritma SHA-256.
     * 
     * @param password Password asli yang ingin di-hash
     * @return Password dalam bentuk hash SHA-256
     */
    public static String passwordHash(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hashed = md.digest(password.getBytes());

            StringBuilder sb = new StringBuilder();
            for (byte b : hashed) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("SHA-256 algorithm not found.");
        }
    }
    
    /**
    * Event handler untuk checkbox "Show Password".
    * Jika checkbox dicentang, maka isi password akan ditampilkan (tidak disensor).
    * Jika tidak dicentang, isi password disembunyikan kembali menggunakan karakter ●.
    * Password hanya ditampilkan atau disembunyikan jika isinya bukan teks placeholder "Password".
    * 
    * @param evt Event yang dipicu saat checkbox di-klik.
    */
    private void cbxShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxShowPasswordActionPerformed
        // TODO add your handling code here:
        String pass = new String(txtPasswordLog.getPassword());
        if (cbxShowPassword.isSelected()) {
            if (!pass.equals("Password")) {
                txtPasswordLog.setEchoChar((char) 0); // tampilkan isi password
            }
        } else {
            if (!pass.equals("Password")) {
                txtPasswordLog.setEchoChar('●'); // sembunyikan isi password
            }
        }
    }//GEN-LAST:event_cbxShowPasswordActionPerformed

    /**
     * Event handler untuk tombol "Sign Up".
     * Ketika tombol ditekan, akan membuka form pendaftaran akun baru (FormSignUp),
     * dan form login saat ini akan ditutup (dispose).
     * 
     * @param evt Event yang dipicu saat tombol "Sign Up" ditekan.
     */
    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        new FormSignUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * Fungsi utama untuk menjalankan form login.
     * 
     * @param args argumen dari baris perintah (tidak digunakan di sini).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JCheckBox cbxShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtPasswordLog;
    private javax.swing.JTextField txtUsernameLog;
    // End of variables declaration//GEN-END:variables
}
