/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javabeans.makeorder;

/**
 * Kelas KeranjangCard
 *
 * Komponen JPanel ini merepresentasikan satu item dalam keranjang belanja,
 * menampilkan nama item, jumlah, harga total, serta menyediakan tombol untuk menghapus item.
 *
 * Digunakan di dalam panel keranjang pada halaman pemesanan.
 *
 * @author alfar
 */
public class KeranjangCard extends javax.swing.JPanel {
    private String nama;
    private String kategori;
    private int harga;
    private int jumlah;
    private KeranjangListener listener;
    
    /**
     * Interface untuk menangani aksi penghapusan item dari keranjang.
     */
    public interface KeranjangListener {
        /**
         * Dipanggil ketika item keranjang dihapus.
         *
         * @param card objek KeranjangCard yang dihapus
         */
        void onItemRemoved(KeranjangCard card);
     }
    

    /**
     * Creates new form KeranjangCard
     * Konstruktor KeranjangCard
     *
     * @param nama   nama item
     * @param harga  harga satuan item
     * @param jumlah jumlah item yang dipesan
     */
    public KeranjangCard(String nama, int harga, int jumlah) {
        initComponents();
        
        this.nama = nama;
        this.harga = harga;
        this.jumlah = jumlah;
        
        namaLabel.setText(nama);
        updateView();
    }
   
    /**
     * Menyimpan listener untuk menangani aksi penghapusan item.
     *
     * @param listener objek yang mengimplementasikan interface KeranjangListener
     */
    public void setKeranjangListener(KeranjangListener listener){
        this.listener = listener;
    }
    
    /**
     * Menghitung total harga (subtotal) dari item.
     *
     * @return harga x jumlah
     */
    public int getSubtotal(){
        return this.harga * this.jumlah;
    }
    
    public String getNama(){
        return this.nama;
    }
    
    public int getHarga(){
        return this.harga;
    }
    
    public int getJumlah(){
        return this.jumlah;
    }
        
    /**
     * Mengubah jumlah item dan tidak langsung memanggil updateView().
     *
     * @param jumlah jumlah baru
     */
    public void setJumlah(int jumlah){
        this.jumlah = jumlah;
    }
        
    /**
     * Memperbarui tampilan label jumlah dan harga total di komponen UI.
     */
    public void updateView(){
        jumlahKeranjang .setText("x" + this.jumlah);
        hargaLabel.setText("Rp " + (this.harga * this.jumlah));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaLabel = new javax.swing.JLabel();
        jumlahKeranjang = new javax.swing.JLabel();
        hargaLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 243, 224));

        namaLabel.setText("jLabel1");
        namaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        namaLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(namaLabel);

        jumlahKeranjang.setText("jLabel1");
        add(jumlahKeranjang);

        hargaLabel.setText("jLabel1");
        add(hargaLabel);

        jButton1.setText("Delete");
        jButton1.setPreferredSize(new java.awt.Dimension(70, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Dipanggil ketika tombol "Delete" ditekan.
     * Memicu event listener jika diset.
     *
     * @param evt event klik tombol
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(listener != null){
            listener.onItemRemoved(this);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jumlahKeranjang;
    private javax.swing.JLabel namaLabel;
    // End of variables declaration//GEN-END:variables
}
