/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javabeans;

/**
 *
 * @author alfar
 */
public class KeranjangCard extends javax.swing.JPanel {

    /**
     * Creates new form KeranjangCard
     */
    public KeranjangCard(String nama, int harga, int jumlah) {
        initComponents();
        
        namaLabel.setText(nama);
        jumlahKeranjang.setText("x" + (Integer) jumlah);
        hargaLabel.setText("Rp + " + harga);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaLabel = new javax.swing.JLabel();
        jumlahKeranjang = new javax.swing.JLabel();
        hargaLabel = new javax.swing.JLabel();

        namaLabel.setText("jLabel1");
        add(namaLabel);

        jumlahKeranjang.setText("jLabel1");
        add(jumlahKeranjang);

        hargaLabel.setText("jLabel1");
        add(hargaLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JLabel jumlahKeranjang;
    private javax.swing.JLabel namaLabel;
    // End of variables declaration//GEN-END:variables
}
