/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javabeans.addmenu;

import javabeans.homepage.HomePageFrame;
import java.sql.*;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Kelas AddMenuFrame
 * Digunakan untuk menambahkan data menu baru ke dalam database aplikasi JavaBeans.
 * Pengguna dapat mengisi nama menu, kategori, harga, dan memilih gambar untuk menu tersebut.
 * Setelah berhasil, data disimpan ke database tabel
 * @author alfar
 */
public class AddMenuFrame extends javax.swing.JFrame {

    private String selectedImagePath;
    private int idUserLogin;
    
    /**
     * Creates new form AddOrderFrame
     * Konstruktor AddMenuFrame
     * 
     * @param idUser ID pengguna yang sedang login
     */
    public AddMenuFrame(int idUser) {
        initComponents();
        this.idUserLogin = idUser;
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNamaMenu = new javax.swing.JTextField();
        cmbKategori = new javax.swing.JComboBox<>();
        txtHarga = new javax.swing.JTextField();
        btnSaveMenu = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnPilihGambar = new javax.swing.JButton();
        lblGambar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(78, 52, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 243, 224));
        jLabel1.setText("Add New Menu!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 62, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 243, 224));
        jLabel2.setText("Name Menu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 111, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 243, 224));
        jLabel3.setText("Category");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 154, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 243, 224));
        jLabel4.setText("Price");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 198, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 243, 224));
        jLabel5.setText("Choose Image");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 242, -1, -1));
        jPanel1.add(txtNamaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 111, 228, -1));

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Category", "Coffee", "Non-Coffee", "Snack", "Food" }));
        jPanel1.add(cmbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 158, 228, -1));
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 202, 228, -1));

        btnSaveMenu.setText("Save");
        btnSaveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 348, -1, -1));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 348, -1, -1));

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 348, -1, -1));

        btnPilihGambar.setText("Choose Image");
        btnPilihGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihGambarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilihGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 246, 121, -1));
        jPanel1.add(lblGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 275, 239, 61));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabeansmanagementsystem/images/gambar-biji-kopi-putih.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-370, 30, 480, 280));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabeansmanagementsystem/images/gambar-biji-kopi-putih.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 410, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Event saat tombol "Choose Image" ditekan.
     * Membuka dialog untuk memilih file gambar lalu menampilkannya di label.
     * 
     * @param evt event klik tombol
     */
    private void btnPilihGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihGambarActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih Gambar");
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Gambar (JPG, PNG, JPEG)", "jpg", "png", "jpeg");
        fileChooser.setFileFilter(filter);
        
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();

        // Tampilkan gambar ke JLabel (misalnya lblGambar adalah JLabel kamu)
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));
            lblGambar.setIcon(imageIcon);

        // (Opsional) Simpan path ke variabel untuk disimpan ke database nanti
            selectedImagePath = selectedFile.getAbsolutePath();
            System.out.println("Path gambar: " + selectedImagePath);
        }
    }//GEN-LAST:event_btnPilihGambarActionPerformed
    
    /**
     * Event saat tombol "Save" ditekan.
     * Melakukan validasi form dan menyimpan data menu ke database jika valid.
     * 
     * @param evt event klik tombol
     */
    private void btnSaveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMenuActionPerformed
        // TODO add your handling code here:
        String namaMenu = txtNamaMenu.getText();
        String kategoriMenu = cmbKategori.getSelectedItem().toString();
        String harga = txtHarga.getText();
        
        
        if (namaMenu.isEmpty() || kategoriMenu.isEmpty() || harga.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data can not be empty!", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (namaMenu.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(this, "Menu name must not contain numbers", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(cmbKategori.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Please select a category", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!harga.matches("\\d+(\\.\\d+)?")){
             JOptionPane.showMessageDialog(this, "Price must contain only numbers", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javabeans", "root", "");
            String sql = "INSERT INTO javabeans_menu (category_menu, nama_menu, harga_menu, gambar_menu) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, kategoriMenu);
            pst.setString(2, namaMenu);
            pst.setString(3, harga);
            
            if (selectedImagePath != null){
                FileInputStream fis = new FileInputStream(new File(selectedImagePath));
                pst.setBinaryStream(4, fis, (int) new File(selectedImagePath).length());
            } else {
                pst.setNull(4, java.sql.Types.BLOB);
            }
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Menu data was saved successfully");
        } catch (Exception e){
            
        }
    }//GEN-LAST:event_btnSaveMenuActionPerformed
    
    /**
     * Event saat tombol "Cancel" ditekan.
     * Kembali ke halaman HomePageFrame.
     * 
     * @param evt event klik tombol
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new HomePageFrame(idUserLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * Event saat tombol "Clear" ditekan.
     * Mengosongkan semua input field dan reset gambar.
     * 
     * @param evt event klik tombol
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtNamaMenu.setText("");
        txtHarga.setText("");
        cmbKategori.setSelectedIndex(0);
        lblGambar.setIcon(null);
        selectedImagePath = null;
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddMenuFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPilihGambar;
    private javax.swing.JButton btnSaveMenu;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNamaMenu;
    // End of variables declaration//GEN-END:variables
}
