/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javabeans.seetransaction;


import java.sql.*;
import javabeans.homepage.HomePageFrame;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 * Kelas OrderFrame
 * JFrame yang digunakan untuk menampilkan daftar transaksi atau pesanan yang sudah dilakukan.
 * Menampilkan ID transaksi, daftar menu, jumlah item, dan total harga setiap transaksi.
 * Admin atau kasir dapat menggunakan tampilan ini untuk melihat histori pesanan.
 *
 * Data diambil dari join tabel order_detail dan javabeans_menu, lalu ditampilkan dalam JTable.
 *
 * @author Haichal Abbrar
 */
public class OrderFrame extends javax.swing.JFrame {
    private int idUserLogin;
    /**
     * Konstruktor untuk OrderFrame
     * Mengatur tampilan dan mengisi tabel dengan data transaksi.
     * @param idUser ID pengguna yang sedang login (digunakan untuk kembali ke HomePageFrame)
     */
    public OrderFrame(int idUser) {
        initComponents();
        this.idUserLogin = idUser;
        tampilkanDataTabel();
    }
    /**
     * Menampilkan data transaksi ke dalam tabel tblOrder.
     * Data mencakup ID transaksi, daftar nama menu, jumlah item, dan total harga,
     * yang dihitung dari hasil join dan agregasi tabel order_detail dan javabeans_menu.
     * Juga mengatur perataan dan lebar kolom pada tabel.
     */
    public void tampilkanDataTabel(){
         DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("List Menu");
            model.addColumn("Amount");
            model.addColumn("Total");
            
            try{
                 Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javabeans", "root", "");
                Statement stmt = conn.createStatement();
                String sql = "SELECT od.id_transaksi, " +
                     "GROUP_CONCAT(m.nama_menu SEPARATOR ', ') AS daftar_menu, " +
                     "SUM(od.jumlah) AS total_item, " +
                     "SUM(od.sub_total) AS total_harga " +
                     "FROM order_detail od " +
                     "JOIN javabeans_menu m ON od.id_menu = m.id " +
                     "GROUP BY od.id_transaksi";
      
                ResultSet rs = stmt.executeQuery(sql);
                
                while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_transaksi"),
                    rs.getString("daftar_menu"),
                    rs.getInt("total_item"),
                    rs.getInt("total_harga")
                });
            }
                tblOrder.setModel(model); 
                
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

                TableColumnModel columnModel = tblOrder.getColumnModel();
                columnModel.getColumn(2).setCellRenderer(centerRenderer); // Jumlah Item
                columnModel.getColumn(3).setCellRenderer(centerRenderer); // Total Harga

                columnModel.getColumn(0).setPreferredWidth(80);   // ID Transaksi
                columnModel.getColumn(1).setPreferredWidth(300);  // List Menu
                columnModel.getColumn(2).setPreferredWidth(100);  // Jumlah Item
                columnModel.getColumn(3).setPreferredWidth(150);  // Total Harga
                
                JTableHeader header = tblOrder.getTableHeader();
                DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) header.getDefaultRenderer();
                headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
                
                rs.close();
                stmt.close();
                conn.close();
            }catch (Exception e){
                e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("List Order");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(78, 52, 46));

        tblOrder.setBackground(new java.awt.Color(255, 243, 224));
        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "List Menu", "Amount", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrder);
        if (tblOrder.getColumnModel().getColumnCount() > 0) {
            tblOrder.getColumnModel().getColumn(0).setMinWidth(40);
            tblOrder.getColumnModel().getColumn(0).setMaxWidth(60);
            tblOrder.getColumnModel().getColumn(1).setMinWidth(200);
            tblOrder.getColumnModel().getColumn(1).setMaxWidth(400);
            tblOrder.getColumnModel().getColumn(2).setMinWidth(50);
            tblOrder.getColumnModel().getColumn(2).setMaxWidth(70);
            tblOrder.getColumnModel().getColumn(3).setMinWidth(80);
            tblOrder.getColumnModel().getColumn(3).setMaxWidth(120);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 243, 224));
        jLabel1.setText("List Order");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(341, 341, 341))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Event handler untuk tombol "Back".
     * Akan menutup OrderFrame dan membuka kembali HomePageFrame dengan ID user login yang sama.
     * 
     * @param evt event klik tombol back
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new HomePageFrame(idUserLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Fungsi main untuk menjalankan frame secara mandiri.
     * Digunakan untuk testing jika diperlukan.
     * 
     * @param args argumen command line (tidak digunakan)
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OrderFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrder;
    // End of variables declaration//GEN-END:variables
}