package javabeansmanagementsystem;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author HAFIS HENDRIANSYAH
 */
public class FormSignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public FormSignUp() {
        initComponents();
        
    txtPasswordSign.setEchoChar((char) 0); // Supaya "Password" terlihat

    // Fokus awal ke panel supaya placeholder tidak langsung hilang
    this.addWindowFocusListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowGainedFocus(java.awt.event.WindowEvent e) {
            jPanel1.requestFocusInWindow();
        }
    });

    // Placeholder First Name
    txtNameSign.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtNameSign.getText().equals("Name")) {
                txtNameSign.setText("");
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtNameSign.getText().isEmpty()) {
                txtNameSign.setText("Name");
            }
        }
    });

    // Placeholder Last Name
    txtUsernameSign.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtUsernameSign.getText().equals("User Name")) {
                txtUsernameSign.setText("");
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtUsernameSign.getText().isEmpty()) {
                txtUsernameSign.setText("User Name");
            }
        }
    });

    // Placeholder Email
    txtEmailSign.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtEmailSign.getText().equals("Email")) {
                txtEmailSign.setText("");
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtEmailSign.getText().isEmpty()) {
                txtEmailSign.setText("Email");
            }
        }
    });

    // Placeholder Password
    txtPasswordSign.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            String pass = new String(txtPasswordSign.getPassword());
            if (pass.equals("Password")) {
        txtPasswordSign.setText("");
            if (cbxShowPassword.isSelected()) {
            txtPasswordSign.setEchoChar((char) 0);
        } else {
            txtPasswordSign.setEchoChar('●');
            }
        }
    }
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            String pass = new String(txtPasswordSign.getPassword());
            if (pass.isEmpty()) {
                txtPasswordSign.setText("Password");
                txtPasswordSign.setEchoChar((char) 0);
            }
        }
    });
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNameSign = new javax.swing.JTextField();
        txtUsernameSign = new javax.swing.JTextField();
        txtEmailSign = new javax.swing.JTextField();
        txtPasswordSign = new javax.swing.JPasswordField();
        btnCreateAccount = new javax.swing.JButton();
        cbxShowPassword = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(78, 52, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create an account");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Already have an account?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, 20));

        txtNameSign.setBackground(new java.awt.Color(255, 243, 224));
        txtNameSign.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNameSign.setText("Name");
        jPanel1.add(txtNameSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 320, 30));

        txtUsernameSign.setBackground(new java.awt.Color(255, 243, 224));
        txtUsernameSign.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtUsernameSign.setText("User Name");
        txtUsernameSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameSignActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsernameSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 320, 30));

        txtEmailSign.setBackground(new java.awt.Color(255, 243, 224));
        txtEmailSign.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEmailSign.setText("Email");
        jPanel1.add(txtEmailSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 318, 30));

        txtPasswordSign.setBackground(new java.awt.Color(255, 243, 224));
        txtPasswordSign.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPasswordSign.setText("Password");
        jPanel1.add(txtPasswordSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 318, 30));

        btnCreateAccount.setBackground(new java.awt.Color(255, 242, 196));
        btnCreateAccount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCreateAccount.setText("Crate account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 250, 30));

        cbxShowPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbxShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        cbxShowPassword.setText("Show Password");
        cbxShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxShowPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(cbxShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 50, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 769, 407));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameSignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameSignActionPerformed

    private void cbxShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxShowPasswordActionPerformed
        // TODO add your handling code here:
        String pass = new String(txtPasswordSign.getPassword());
        if (cbxShowPassword.isSelected()) {
            if (!pass.equals("Password")) {
                txtPasswordSign.setEchoChar((char) 0); // tampilkan isi password
            }
        } else {
            if (!pass.equals("Password")) {
                txtPasswordSign.setEchoChar('●'); // sembunyikan isi password
            }
        }
    }//GEN-LAST:event_cbxShowPasswordActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        String name = txtNameSign.getText();
        String userName = txtUsernameSign.getText();
        String email = txtEmailSign.getText();
        String password = new String(txtPasswordSign.getPassword());
        
        if (name.equals("Name") || userName.equals("User Name") || email.equals("Email") || password.equals("Password") ||
            name.isEmpty() || userName.isEmpty() || email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong", "Message", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!name.matches("[a-zA-Z\\s]+")) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh mengandung angka atau simbol", "Message", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!email.matches("^[A-Za-z0-9._%+-]+@(gmail\\.com|yahoo\\.com|outlook\\.com)$")) {
            JOptionPane.showMessageDialog(this, "Format email tidak valid (hanya gmail/yahoo/outlook)", "Message", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(password.length() < 8){
            JOptionPane.showMessageDialog(this, "Password minimal 8 karakter", "Message", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        try {
            SignUp signUp = new SignUp(name, userName, email, password);
            Connection conn = Koneksi.getConnection();

            String cekUsername = "SELECT * FROM akun WHERE username = ?";
            String cekEmail = "SELECT * FROM akun WHERE email = ?";

            PreparedStatement psUserName = conn.prepareStatement(cekUsername);
            psUserName.setString(1, signUp.username);
            ResultSet rsUserName = psUserName.executeQuery();

            if (rsUserName.next()) {
                JOptionPane.showMessageDialog(this, "Username ini telah digunakan", "Message", JOptionPane.INFORMATION_MESSAGE);
            } else {
                PreparedStatement psEmail = conn.prepareStatement(cekEmail);
                psEmail.setString(1, signUp.email);
                ResultSet rsEmail = psEmail.executeQuery();

            if (rsEmail.next()) {
                JOptionPane.showMessageDialog(this, "Email ini telah digunakan", "Message", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Jika username dan email belum digunakan, insert akun baru
                String insert = "INSERT INTO akun (name_user, username, email, password_user) VALUES (?, ?, ?, ?)";
                PreparedStatement psInsert = conn.prepareStatement(insert);
                psInsert.setString(1, signUp.nameUser);
                psInsert.setString(2, signUp.username);
                psInsert.setString(3, signUp.email);
                psInsert.setString(4, signUp.passwordUser);

                psInsert.executeUpdate();
                JOptionPane.showMessageDialog(this, "Akun berhasil dibuat", "Sign Up", JOptionPane.INFORMATION_MESSAGE);
                
                // Reset semua input
                txtNameSign.setText("Name");
                txtUsernameSign.setText("User Name");
                txtEmailSign.setText("Email");
                txtPasswordSign.setText("Password");
                }
            }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JCheckBox cbxShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmailSign;
    private javax.swing.JTextField txtNameSign;
    private javax.swing.JPasswordField txtPasswordSign;
    private javax.swing.JTextField txtUsernameSign;
    // End of variables declaration//GEN-END:variables
}
