/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javabeansmanagementsystem;

import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author HAFIS HENDRIANSYAH
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public FormLogin() {
        initComponents();
        
    this.addWindowFocusListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowGainedFocus(java.awt.event.WindowEvent e) {
            jPanel1.requestFocusInWindow(); // Panel atau komponen lain sebagai fokus awal
        }
    });
        
    txtPasswordLog.setEchoChar((char) 0); // Biar tulisan Password terlihat

    // Placeholder behavior untuk jTextField1 (Username)
    txtUsernameLog.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtUsernameLog.getText().equals("Username")) {
                txtUsernameLog.setText("");
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtUsernameLog.getText().isEmpty()) {
                txtUsernameLog.setText("Username");
            }
        }
    });

    // Placeholder behavior untuk jPasswordField1 (Password)
    txtPasswordLog.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            String pass = new String(txtPasswordLog.getPassword());
            if (pass.equals("Password")) {
        txtPasswordLog.setText("");
            if (cbxShowPassword.isSelected()) {
            txtPasswordLog.setEchoChar((char) 0);
        } else {
            txtPasswordLog.setEchoChar('●');
            }
        }
    }
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            String pass = new String(txtPasswordLog.getPassword());
            if (pass.isEmpty()) {
                txtPasswordLog.setText("Password");
                txtPasswordLog.setEchoChar((char) 0); // Tampilkan teks biasa lagi
            }
        }
    });
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtUsernameLog = new javax.swing.JTextField();
        txtPasswordLog = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbxShowPassword = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(78, 52, 46));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hello,");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome!");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("to JavaBeans Management System.");

        jPanel2.setBackground(new java.awt.Color(255, 243, 224));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsernameLog.setBackground(new java.awt.Color(255, 243, 224));
        txtUsernameLog.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtUsernameLog.setForeground(new java.awt.Color(78, 52, 41));
        txtUsernameLog.setText("Username");
        txtUsernameLog.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 52, 46), 3, true));
        txtUsernameLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameLogActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsernameLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 200, 30));

        txtPasswordLog.setBackground(new java.awt.Color(255, 243, 224));
        txtPasswordLog.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPasswordLog.setForeground(new java.awt.Color(78, 52, 41));
        txtPasswordLog.setText("Password");
        txtPasswordLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(78, 52, 46), 3));
        txtPasswordLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordLogActionPerformed(evt);
            }
        });
        jPanel2.add(txtPasswordLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 200, 30));

        btnLogin.setBackground(new java.awt.Color(100, 73, 38));
        btnLogin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, 30));

        btnSignUp.setBackground(new java.awt.Color(249, 242, 213));
        btnSignUp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(78, 52, 46));
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 90, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gambar-biji-kopi.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 150, 160));

        cbxShowPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbxShowPassword.setText("Show Password");
        cbxShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxShowPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(cbxShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("logo javabeans");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameLogActionPerformed

    private void txtPasswordLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordLogActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsernameLog.getText();
        String password = new String(txtPasswordLog.getPassword());
        
        if (username.equals("Username") || password.equals("Password") || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username dan password tidak boleh kosong", "Massage", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(password.length() < 8){
            JOptionPane.showMessageDialog(this, "Password minimal 8 karakter", "Message", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        Login login = new Login(username, password);
        
        try {
            Connection conn = Koneksi.getConnection();
           String query = "SELECT * FROM akun WHERE username=? AND password_user=?";
           PreparedStatement preparedStat = conn.prepareStatement(query);
           preparedStat.setString(1, login.username);
           preparedStat.setString(2, login.password);
           ResultSet resultSet = preparedStat.executeQuery();   
           
        if (resultSet.next()) {
            JOptionPane.showMessageDialog(this, "Halo, " + login.username, "Message", JOptionPane.INFORMATION_MESSAGE);
            new Dashboard().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Pastikan username dan password yang anda masukkan benar", "Warning", JOptionPane.ERROR_MESSAGE);
        }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cbxShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxShowPasswordActionPerformed
        // TODO add your handling code here:
        String pass = new String(txtPasswordLog.getPassword());
        if (cbxShowPassword.isSelected()) {
            if (!pass.equals("Password")) {
                txtPasswordLog.setEchoChar((char) 0); // tampilkan isi password
            }
        } else {
            if (!pass.equals("Password")) {
                txtPasswordLog.setEchoChar('●'); // sembunyikan isi password
            }
        }
    }//GEN-LAST:event_cbxShowPasswordActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        new FormSignUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JCheckBox cbxShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtPasswordLog;
    private javax.swing.JTextField txtUsernameLog;
    // End of variables declaration//GEN-END:variables
}
